### ISSUE TITLE
[Bug] Changes the font of monospace areas

### ISSUE THREAD

**Issue by rauenzi** [notmike101/betterdiscord-google-fonts#1]
The selector used `*` in combination with `!important` means that monospace areas like the css editor and codeblocks in-chat get overridden with the google font chosen. I would recommend changing the selector to something like `::placeholder, body, button, input, select, textarea`

**Comment by notmike101** [comment]
Maybe a setting to exclude replacing monospace font areas? I'll likely end up removing `!important` with more specific rules as well.

I, personally, am fine with having the font replaced everywhere, even if it's intended to be monospace.

**Comment by notmike101** [comment]
#4 Addresses this related to codeblocks.
