### ISSUE TITLE
Missing font

### ISSUE THREAD

**Issue by S0phistication** [notmike101/betterdiscord-google-fonts#10]
PLEASE ADD "Times New Roman (Cyr)" font!

If that's not possible, that's fine, above all, this plugin works perfectly on Discord, literally that's all I ask for for this masterpiece.

**Comment by notmike101** [comment]
Times New Roman (Cyr) is not part of Google Fonts, so this will not be done.

For a full list of fonts, see here:
https://fonts.google.com
