### ISSUE TITLE
[Bug] Can't select Google Fonts in BetterDiscord

### ISSUE THREAD

**Issue by BiBi88** [notmike101/betterdiscord-google-fonts#3]
Currently not working. 

Can't select fonts from the drop down menu. No fonts active even if plugin is active.

Not working on Discord versions:

Stable 101451 (b46c230)

Ptb 101451 (b46c230)

**Comment by notmike101** [comment]
Will look at this tonight and see what's going on.

**Comment by BiBi88** [comment]
Just checked on both stable and Ptb versions and it seems to be working again.

**Comment by notmike101** [comment]
> Just checked on both stable and Ptb versions and it seems to be working again.

@BiBi88 That's what I was getting as well, wasn't sure if it was my client or not.

Thank you for confirming, if issue comes back, please let me know.

**Comment by ninjasan420** [comment]
Hi there,

it is not working again. Disabling/enabling the plugin doesn't work, which did a few days back :)

Maybe you can try to find the issue and fix it. Thanks!

**Comment by notmike101** [comment]
> Hi there @notmike101,
> 
> it is not working again. Disabling/enabling the plugin doesn't work, which did a few days back :)
> 
> Maybe you can try to find the issue and fix it. Thanks!

Any errors that you're seeing or just a silent failure?

**Comment by ninjasan420** [comment]
No errors at all. It's pretty much the same error as discribed by OP: I can't select any font anymore, except for the Default one which is pre-selected. Also, disabling and re-enabling the script doesn't work :(

**Comment by notmike101** [comment]
@ninjasan420 Thanks for confirming it works now. I haven't changed anything on this, might have just been a Discord issue.

Let me know if it happens again.

**Comment by ashergz** [comment]
> @ninjasan420 Thanks for confirming it works now. I haven't changed anything on this, might have just been a Discord issue.
> 
> Let me know if it happens again.

It's happening again. Please diagnose the root cause of this issue and fix it once and for all.

**Comment by huangdangwibu** [comment]
> > Hi there @notmike101,
> > it is not working again. Disabling/enabling the plugin doesn't work, which did a few days back :)
> > Maybe you can try to find the issue and fix it. Thanks!
> 
> Any errors that you're seeing or just a silent failure?

i got an error:
Uncaught (in promise) TypeError: Cannot read property 'map' of undefined
    at DiscordPlugin.getAvailableFonts (betterdiscord-google-fonts.plugin.js:77)
    at async DiscordPlugin.start (betterdiscord-google-fonts.plugin.js:60)

**Comment by minxuanchua** [comment]
Now because of discord update, there is a problem with the plugin and the font cannot be adjusted

**Comment by notmike101** [comment]
Looking at this again, sorry for the delay.

I'm actually rebuilding this entire plugin to make my life easier in the future as well.

**Comment by ashergz** [comment]
Thanks great news! Thanks for doing this.

**Comment by Inui-senpai** [comment]
The plugin stopped working today. Redownloaded it from the GitHub and replaced it in my Plugins folder, and it works again.

Glad to hear that you're currently rebuilding it. I hope it wouldn't break again before rebuilded release, because Discord's new font without cyrillic support pisses me off.

**Comment by syiona** [comment]
the plugin doesn't work for me anymore even after deleting it and redownloading it and restarting discord. :(

**Comment by Inui-senpai** [comment]
> the plugin doesn't work for me anymore even after deleting it and redownloading it and restarting discord. :(

Is BetterDiscord working? Try to repair it. 🤔

**Comment by syiona** [comment]
> > the plugin doesn't work for me anymore even after deleting it and redownloading it and restarting discord. :(
> 
> Is BetterDiscord working? Try to repair it. 🤔

yep i’ve tried repairing it several times too

**Comment by Inui-senpai** [comment]
> yep i’ve tried repairing it several times too

Mhm, I see. I think it's the Google Fonts API's quota exceeding problem after all. Disabling the plugin and enabling it again after a while seems to return its functionality.

**Comment by notmike101** [comment]
> > yep i’ve tried repairing it several times too
> 
> Mhm, I see. I think it's the Google Fonts API's quota exceeding problem after all. Disabling the plugin and enabling it again after a while seems to return its functionality.

You're correct, that is the core issue here. I'm still trying to figure out the best solution for this without having to require each user to have their own API key and without hosting this data on any of my servers.

**Comment by notmike101** [comment]
Just released V2.0.0 via PR #13 which has resolved this issue.

If anyone wants to test it, please do so and let me know if you find any bugs by creating a new issue.
