### ISSUE TITLE
Plugin broken again

### ISSUE THREAD

**Issue by ashergz** [notmike101/betterdiscord-google-fonts#32]
Same issue as last time. Custom font cannot be set. The dropdown menu to select font in the plugin setting does not open. Please look into this.

![image](https://user-images.githubusercontent.com/35883201/168410247-81f4a42d-e57b-42e4-bd59-c1d24e5ceae0.png)

**Comment by notmike101** [comment]
Are you using V2 of the plugin or V1?

**Comment by ashergz** [comment]
V1. V2 is still not available on bd plugin repository and can't seem to access it from this link. https://github.com/notmike101/betterdiscord-google-fonts/blob/release/google-fonts.plugin.js
![SmartSelect_20220524-161304_Chrome](https://user-images.githubusercontent.com/35883201/170022327-29b03e55-13fb-4126-89c3-6282a0d3a285.jpg)

**Comment by notmike101** [comment]
See #22 for why this isn't available on repository yet.

https://raw.githubusercontent.com/notmike101/betterdiscord-google-fonts/release/betterdiscord-google-fonts.plugin.js

This is the direct path to the plugin. Not sure where you got the URL you sent.

Let me know if it works.

**Comment by ashergz** [comment]
That URL is from the very thread you linked: #22

As for the plugin, it works but is missing quite a few Google fonts, including the one I normally use: https://fonts.google.com/specimen/Autour+One

Any reason why that is the case?
