### ISSUE TITLE
Missing Fonts

### ISSUE THREAD

**Issue by notmike101** [notmike101/betterdiscord-google-fonts#35]
Works but is missing quite a few Google fonts, including the one I normally use: https://fonts.google.com/specimen/Autour+One

Any reason why that is the case?

_Originally posted by @ashergz in https://github.com/notmike101/betterdiscord-google-fonts/issues/32#issuecomment-1136262621_

**Comment by notmike101** [comment]
@ashergz I'm seeing the font you mentioned here.
Can you confirm that it's not showing up, even in a search for "Autor"?

![image](https://user-images.githubusercontent.com/7198316/170124822-10ef393f-5c61-4d91-aa0a-235b36034cdc.png)

**Comment by chanhh01** [comment]
Meanwhile mine only shows default, is there any way i can edit the source code in the plugin to make sure the plugin defaults at the font i want? Not that familiar with JS and betterdiscord API

**Comment by notmike101** [comment]
> Meanwhile mine only shows default, is there any way i can edit the source code in the plugin to make sure the plugin defaults at the font i want? Not that familiar with JS and betterdiscord API

I've created a new issue for you, we can continue discussing there.

**Comment by ashergz** [comment]
> @ashergz I'm seeing the font you mentioned here. Can you confirm that it's not showing up, even in a search for "Autor"?
> 
> ![image](https://user-images.githubusercontent.com/7198316/170124822-10ef393f-5c61-4d91-aa0a-235b36034cdc.png)

Works now. I dunno why the font wasn't showing up before. Now though, there's another issue. I use a theme with custom font and unlike v1, the selected font in the plugin can't seem to override it. Can you please look into it?

**Comment by notmike101** [comment]
Great to hear that it's working now, odd that it wasn't before. Possibly just a build issue. Every release should have an updated fonts list, so that shouldn't be an issue in the future.

I've also created a new issue for the second problem you mentioned (#40) and will be closing this one to keep issue tracker clean.
