### ISSUE TITLE
Settings only shows "Default" as available

### ISSUE THREAD

**Issue by notmike101** [notmike101/betterdiscord-google-fonts#37]
Mine only shows default, is there any way i can edit the source code in the plugin to make sure the plugin defaults at the font i want? Not that familiar with JS and betterdiscord API

_Originally posted by @chanhh01 in https://github.com/notmike101/betterdiscord-google-fonts/issues/35#issuecomment-1138124930_

**Comment by notmike101** [comment]
@chanhh01 If you're not familiar with JavaScript or typescript, modifying the plugin will be fairly difficult for you to accomplish. If that's a task you'd like to take on, just fork this repository, clone to your own machine, modify, and build.

As for the issue you're experiencing, are you using V1 or V2? V1 has several known issues that have been resolved with V2, but V2 is not available on the betterdiscord website at this time due to what's described in #22 .

**Comment by chanhh01** [comment]
@notmike101 im currently still using V1.0.2 that is provided in BD plugins, this is not the first time i experienced such issue. Before this I assumed it to be API issue so I would just either wait or restart discord to fix the issue. 
modifying the whole repository is kinda hard for me especially i have little experience on JS and no experience on BD API, i guess i'll give up on that then

**Comment by notmike101** [comment]
@chanhh01 You're correct on it being an API issue, specifically over-use of my developer Google Fonts API token.

Please use V2 of the plugin. The issue was resolved with V2 release and is pending approval for the BD plugin repo (#22)

https://github.com/notmike101/betterdiscord-google-fonts/blob/release/betterdiscord-google-fonts.plugin.js

**Comment by chanhh01** [comment]
@notmike101 do i copy and paste the content?? I kinda hesitated when i saw the nested json, i thought the nested json is in .config json file?
Btw the .config json file looked like this, is it supposed to be like that?
![image](https://user-images.githubusercontent.com/84566394/170442041-843a1199-d7e1-4858-9695-2f7854cc6006.png)

**Comment by notmike101** [comment]
@chanhh01 You can safely delete the config.json file. The only side effect is that you lose any current settings.

To install the plugin, save the file that was posted earlier, open your plugin folder, and put the saved file there, overwriting any existing file with the same name.

If there's any other issues, please let me know.

**Comment by chanhh01** [comment]
@notmike101  i did it, but i cannot open the settings

**Comment by notmike101** [comment]
> @notmike101 i did it, but i cannot open the settings

Can you create a new issue for that?
