### ISSUE TITLE
Plugin not overwriting theme fonts

### ISSUE THREAD

**Issue by notmike101** [notmike101/betterdiscord-google-fonts#40]
> @ashergz I'm seeing the font you mentioned here. Can you confirm that it's not showing up, even in a search for "Autor"?
> 
> ![image](https://user-images.githubusercontent.com/7198316/170124822-10ef393f-5c61-4d91-aa0a-235b36034cdc.png)

Works now. I dunno why the font wasn't showing up before. Now though, there's another issue. I use a theme with custom font and unlike v1, the selected font in the plugin can't seem to override it. Can you please look into it?

_Originally posted by @ashergz in https://github.com/notmike101/betterdiscord-google-fonts/issues/35#issuecomment-1138180581_

**Comment by chanhh01** [comment]
Wait i didnt mention #35 is solved XDD
i only said that previously this could be solved by restarting discord, but the issue did not go away this time 
this is why i commented there XD

**Comment by ashergz** [comment]
I mean the plugin is designed to change the font and that's what anyone using it expects it to do? If they want to retain the theme font, they will just disable the plugin? right now, there isn't any way to use a theme but with the font of our choice which I believe is something people would want.

**Comment by notmike101** [comment]
Makes sense, the only issue I can see with this type of solution is that I'm not sure how themes are applying fonts, so I wouldn't be able to apply it consistently.

As of right now, the plugin works by overwriting some of Discord's CSS variables, specifically `--font-primary`, `--font-display`, and `--font-headline`.

In order for me to figure out the most common way that themes are overwriting fonts, @ashergz, can you let me know what theme you're using and provide a link to it if possible?

**Comment by notmike101** [comment]
@ashergz Can you try the new version 2.0.11 and let me know if that's more acceptable?

**Comment by ashergz** [comment]
Yup, this is perfect. Thanks!
