### ISSUE TITLE
Setting could not be opened for GoogleFonts v2.0.7

### ISSUE THREAD

**Issue by chanhh01** [notmike101/betterdiscord-google-fonts#43]
![image](https://user-images.githubusercontent.com/84566394/170451135-5487e330-7810-4ccf-ac33-697ddc0552b7.png)

**Comment by notmike101** [comment]
Do you by chance have the ability to open the developer console (CTRL+SHIFT+I)?

If so, would you be able to report any errors that show up after you attempt to open the settings panel?

If not, I'll have to look into this tomorrow.

**Comment by chanhh01** [comment]
@notmike101 nope, i have no idea how to work on it lol, i dont even have NodeJS installed, if it's simple i can try it.

**Comment by chanhh01** [comment]
and also i deleted the .config json as you suggested

**Comment by notmike101** [comment]
Fixed this, will be pushing up a fix in a few minutes.

For context, the issue was the lack of `import { React } from 'betterdiscord/bdapi'` in the code, so the typescript compiler assumed to use normal React.

**Comment by notmike101** [comment]
Please download v2.0.8 to resolve this issue

https://github.com/notmike101/betterdiscord-google-fonts/releases/download/v2.0.8/betterdiscord-google-fonts.plugin.js

**Comment by chanhh01** [comment]
@notmike101 thank you for fixing the issue!
