### ISSUE TITLE
[Bug] Plugin does not overwrite theme fonts

### ISSUE THREAD

**Issue by DaVouz** [notmike101/betterdiscord-google-fonts#46]
plugin doesn't work. I am changing the fonts but nothing happens   tried to delete it and re install it and even downloading older versions  idk what is wrong with it

**Comment by notmike101** [comment]
Are there any errors in the developer console?

Are you using the newest version?

Is the plugin enabled?

**Comment by DaVouz** [comment]
don't know how to check the first one 
2nd and 3rd one answer is yes

**Comment by notmike101** [comment]
@DaVouz To Enable DevTools go to BD settings > Developer Settings > DevTools and enable the option

Then press **CTRL + SHIFT + I**. A new window should pop up, head over to the **Console** tab and be sure you've scrolled all the way to the bottom.

Once you have this set up and open., go into settings and disable and reenable the plugin to see any new errors that appear with the plugin.

**Comment by DaVouz** [comment]
it doesn't seem to give me an error for the font plugin    only one other plugin gives me error but for some reason it works

**Comment by notmike101** [comment]
@DaVouz If you go into the settings of the plugin, are you able to change the font that is being used?

Have you tried disabling all other plugins except the Google Fonts plugin to see if the issue still exists?

**Comment by DaVouz** [comment]
i disabled everything but it didn't work  i can select fonts  it's just that it doesn't change the fonts whatever font i select

**Comment by notmike101** [comment]
Are you using any themes?

In the developer log, when you change a font, do you see anything similar to this:
`[GoogleFonts] (2.0.11) Changing font to FontName`?

**Comment by DaVouz** [comment]
well aparewell aparently when i use some  themes the font plugin doesn't work    is it the problem of the new font plugin or is it the theme's problem?

**Comment by notmike101** [comment]
Which theme are you using? If possible, can you share the theme file as an attachment to your comment (Please don't share code in the comment?

Depending on how the theme is working, this plugin may not be compatible with it... There's only so much I can do via a plugin to overwrite theme specified fonts.

**Comment by DaVouz** [comment]
[Spotify-Discord.theme.zip](https://github.com/notmike101/betterdiscord-google-fonts/files/8790102/Spotify-Discord.theme.zip)
yeah sure  this is the theme  it's called spotify discord

**Comment by notmike101** [comment]
The issue is that the theme you're using is setting the `--font-primary` variable that I'm using for the plugin.

https://capnkitten.github.io/BetterDiscord/Themes/Spotify-Discord/css/source.css

What I may need to do is make a custom variable for google fonts that's set everywhere. I'll be experimenting with this to find a resolution to this issue.

**Comment by notmike101** [comment]
@DaVouz Just released v2.0.13. Please try that and let me know if it resolves the issue.

**Comment by DaVouz** [comment]
yes brother  for sure that sure fixed   thank you very much i appreciate it a lot
