### ISSUE TITLE
Selecting Fonts list isn't showing up and keeps it at default.(betterdiscord-google-fonts plugin)

### ISSUE THREAD

**Issue by IamNickerson** [notmike101/betterdiscord-google-fonts#5]
Hi I try to open the fonts list in betterdiscord-google-Fonts settings it wont open and also keeps the Fonts in Default.

**Comment by IamNickerson** [comment]
It is showing an error in the console.
![image](https://user-images.githubusercontent.com/61643704/150666458-5298c4e0-1402-41ef-8e13-a8c013f56aad.png)

**Comment by Kilgorio** [comment]
I have the same issue

**Comment by IamNickerson** [comment]
I think was with assign badges by QWERTYXD because it has having some conflict with it.

**Comment by ashergz** [comment]
> I think the plugin assign badges by QWERTYXD is has having some conflict with it because when I installed assign badges the plugin google-fonts wouldn't work.

Don't have that plugin and still not working for me.

**Comment by huangdangwibu** [comment]
i reloaded the plugin and it somehow worked again, maybe try doing that

**Comment by ashergz** [comment]
> i reloaded the plugin and it somehow worked again, maybe try doing that

Can confirm. That worked. Thanks. A fix would be nice though.

**Comment by IamNickerson** [comment]
It just like it is working but after it doesn't work and after it works it is just like that from me but now it works.

**Comment by IamNickerson** [comment]
Ok I may close this issue since it is now working.
