### ISSUE TITLE
[BUG] Google Fonts not loading (via the BD server)

### ISSUE THREAD

**Issue by SmolAlli** [notmike101/betterdiscord-google-fonts#53]
**Describe the bug**

A user said that the Google Fonts plugin was not working.

**Screenshots**

![image](https://user-images.githubusercontent.com/22519967/170818348-2df21fed-4d25-4db3-b0e8-b94cb0fbf9a9.png)

**Additional context**

Decided to make an issue for you since the person who reported didn't.

**Comment by notmike101** [comment]
Not able to reproduce this. The error is also not related to Google Fonts.

The original reporter was likely using a custom theme that didn't allow the plugin to overwrite the font.

Pushed up a new version that should fix any issues people were having.
