### ISSUE TITLE
[BUG] Menu broken

### ISSUE THREAD

**Issue by DoctorBraingoop** [notmike101/betterdiscord-google-fonts#55]
Notice: If you do not use this template for your issue, it will remain unanswered and be closed.

----

**Describe the bug**

Menu is not showing in fonts settings

**Are you using the latest version of the plugin?**

- [X] Yes
- [ ] No

**Screenshots**
<img width="703" alt="Screen Shot 2022-05-29 at 2 51 04 PM" src="https://user-images.githubusercontent.com/40189403/170886862-911faee9-b58e-448e-85c6-7c78f3bb87cd.png">

**Comment by notmike101** [comment]
You are not using the newest version of the plugin.

Please use the latest version:
https://github.com/notmike101/betterdiscord-google-fonts/releases/latest
