### ISSUE TITLE
GUI not working

### ISSUE THREAD

**Issue by Humper04** [notmike101/betterdiscord-google-fonts#57]
Notice: If you do not use this template for your issue, it will remain unanswered and be closed.

----

**Describe the bug**

If I try to open the font list in settings, it won't open.

**Are you using the latest version of the plugin?**

I am using the latest version of the plugin

**What have you tried to fix the issue?**

I tried removing all my plugins and only using the google fonts plugin, but it didn't work. I tried deleting plugin and reïnstalling it, but it didn't work.

**Steps to reproduce the issue:**

To reproduce, you have to install the plugin and you're done.

**Expected behavior:**

It's supposed to open the font list

**Screenshots**

https://user-images.githubusercontent.com/69055766/171641084-3d29bb5c-1630-45c7-9cb4-1ac8b4d13558.png

**Additional context**

Add any other context that you believe to be necessary to describe the problem.

**Comment by notmike101** [comment]
Use V2

https://raw.githubusercontent.com/notmike101/betterdiscord-google-fonts/release/betterdiscord-google-fonts.plugin.js
