### ISSUE TITLE
[BUG] Missing fonts

### ISSUE THREAD

**Issue by huangdangwibu** [notmike101/betterdiscord-google-fonts#58]
**Describe the bug**

Some fonts are missing and cannot be selected, such as Roboto (https://fonts.google.com/specimen/Roboto) or Noto Sans (https://fonts.google.com/noto/specimen/Noto+Sans)

**Are you using the latest version of the plugin?**

Yes

**What have you tried to fix the issue?**

Reinstalling plugin

**Steps to reproduce the issue:**

Go to settings and search for a font, such as Roboto or Noto Sans

**Expected behavior:**

Font show up and is selectable

**Screenshot**

![image](https://user-images.githubusercontent.com/89643664/171994918-2afb1917-c34f-439b-89dd-53973cbb0891.png)
![image](https://user-images.githubusercontent.com/89643664/171994926-b153ba3e-3725-4047-b80a-5056853dca7a.png)

**Comment by notmike101** [comment]
@huangdangwibu Strange, I'm even using Roboto myself without issue.

Can you go here and tell me what you get:
https://cdn.jsdelivr.net/gh/notmike101/betterdiscord-google-fonts@google-fonts-host/google-fonts.json

Also, can you confirm that you're using v2.2.7 (or later)?

**Comment by huangdangwibu** [comment]
> @huangdangwibu Strange, I'm even using Roboto myself without issue.
> 
> Can you go here and tell me what you get: https://cdn.jsdelivr.net/gh/notmike101/betterdiscord-google-fonts@google-fonts-host/google-fonts.json
> 
> Also, can you confirm that you're using v2.2.7 (or later)?

![image](https://user-images.githubusercontent.com/89643664/172018370-aa233335-5ad3-4f9d-9eba-ebfa9e67367a.png)
![image](https://user-images.githubusercontent.com/89643664/172018403-6980aea2-15bf-4c11-a93a-b9e1712e6a39.png)
![image](https://user-images.githubusercontent.com/89643664/172018423-d236562b-08cf-4a34-b8e6-213d125f84d1.png)

**Comment by huangdangwibu** [comment]
the font im using as a substitute (exo) seems to re enable itself after every reinstall despite me deleting every files related to the plugin in the plugin folder. am i missing something

**Comment by notmike101** [comment]
@huangdangwibu I'm not sure what you mean by a substitute font. Are you selecting another font using the plugin?

Also, are you able to open the developer console and see any errors related to the plugin?

**Comment by huangdangwibu** [comment]
> @huangdangwibu I'm not sure what you mean by a substitute font. Are you selecting another font using the plugin?
> 
> Also, are you able to open the developer console and see any errors related to the plugin?

i meant the font to use temporarily instead of roboto

there are also no errors from the plugin, only info logs

**Comment by huangdangwibu** [comment]
![image](https://user-images.githubusercontent.com/89643664/172038408-3fdb2e9e-eb5c-410a-b39a-3c3466e9b140.png)
update: i lost the font i was using after a discord restart

**Comment by notmike101** [comment]
@huangdangwibu The font search is case sensitive. I'll fix that in the next update.

In the future, please search for "Roboto" instead of "roboto".

**Comment by notmike101** [comment]
Resolved in v2.2.8.
