### ISSUE TITLE
BD Update Seems to have broken this plugin?

### ISSUE THREAD

**Issue by jellyjam14blas** [notmike101/betterdiscord-google-fonts#6]
The select a font pop-up is blank, so it defaults to the normal font.
![Screen Shot 2022-01-24 at 10 28 34 PM](https://user-images.githubusercontent.com/56269179/150923018-ebbbf16c-f378-4b6c-9908-ee52afc1915a.png)
.

**Comment by ashergz** [comment]
The previous workaround of restarting the plugin no longer seems to be working either

**Comment by notmike101** [comment]
Consolidating these issues into one main issue here:
https://github.com/notmike101/betterdiscord-google-fonts/issues/3
