### ISSUE TITLE
( Glitch ) 

### ISSUE THREAD

**Issue by flskystar** [notmike101/betterdiscord-google-fonts#9]
Basically, the settings doesn't let me choose the fonts, i wan't to change to the Ubuntu font but there's only one font name "default" .So how do i fix that thing? its kinda annoying and i can't do anythings.
Things i already try:
Re-install the plugin.
Re-fresh BetterDiscord.
Re-active the plugin.

**Comment by notmike101** [comment]
Merging into #3
